apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "100m" 
        memory: "100Mi" 
      min:
        cpu: "20m" 
        memory: "6Mi" 
    - type: "Container"
      max:
        cpu: "100m" 
        memory: "100Mi" 
      min:
        cpu: "10m" 
        memory: "6Mi" 
      default:
        cpu: "60m" 
        memory: "60Mi" 
      defaultRequest:
        cpu: "20m" 
        memory: "20Mi" 
      maxLimitRequestRatio:
        cpu: "3" 
